// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Aab
    {
        public string AnneeDeb { get; set; }
        public string NiveauScolaires { get; set; }
        public string DateSaisie { get; set; }
        public string DateModif { get; set; }
        public string DomaineEnseigement { get; set; }
        public string Priode { get; set; }
        public string UeEnseignement { get; set; }
        public string DescriptionUe { get; set; }
    }
}