// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class AaTemp
    {
        public string CodeModule { get; set; }
        public string NumPanier { get; set; }
        public string CodeCl { get; set; }
        public string AnneeDeb { get; set; }
        public string AnneeFin { get; set; }
        public string Description { get; set; }
        public string NbHeures { get; set; }
        public string Coef { get; set; }
        public string NumSemestre { get; set; }
        public string NumPeriodfe { get; set; }
        public string DateDebut { get; set; }
        public string DateFin { get; set; }
        public string DateExamen { get; set; }
        public string DateRattrapage { get; set; }
        public string NbHoraireRealises { get; set; }
        public string Acomptabiliser { get; set; }
        public string IdEns { get; set; }
        public string IdEns2 { get; set; }
        public string NbHeuresEns { get; set; }
        public string NbHeuresEns2 { get; set; }
        public string Surveillant { get; set; }
        public string HeureExam { get; set; }
        public string SalleExam { get; set; }
        public string Surveillant2 { get; set; }
        public string SalleExam2 { get; set; }
        public string Periode { get; set; }
        public string Numpromotioncs { get; set; }
        public string ApCs { get; set; }
        public string ChargeP1 { get; set; }
        public string ChargeP2 { get; set; }
        public string ChargeEns1P1 { get; set; }
        public string ChargeEns1P2 { get; set; }
        public string ChargeEns2P1 { get; set; }
        public string ChargeEns2P2 { get; set; }
        public string SeanceUnique { get; set; }
        public string IdEns3 { get; set; }
        public string IdEns4 { get; set; }
        public string IdEns5 { get; set; }
        public string ChargeEns3P1 { get; set; }
        public string ChargeEns3P2 { get; set; }
        public string ChargeEns4P1 { get; set; }
        public string ChargeEns4P2 { get; set; }
        public string ChargeEns5P1 { get; set; }
        public string ChargeEns5P2 { get; set; }
        public string CodeUe { get; set; }
        public string NbEcts { get; set; }
        public string TypeEpreuve { get; set; }
        public string Chargep1add { get; set; }
        public string Chargep2add { get; set; }
        public string CodePlan { get; set; }
        public string Nbheuradd { get; set; }
        public string Salle { get; set; }
        public string ExisteCc { get; set; }
        public string ExisteTp { get; set; }
        public string CalculRat { get; set; }
        public string HeureRat { get; set; }
        public string DateRat { get; set; }
        public string DesignationNew { get; set; }
    }
}