// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Ab
    {
        public string PwdP { get; set; }
        public string IdEt { get; set; }
        public string Nom { get; set; }
        public string Pnom { get; set; }
    }
}