// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class AffectationExamen
    {
        public string Heure { get; set; }
        public DateTime DateExamen { get; set; }
        public decimal NombreHeureExamen { get; set; }
        public string IdEns { get; set; }
        public string Salle { get; set; }
        public string CodeModule { get; set; }
        public string CodeCl { get; set; }
        public string AnneeDeb { get; set; }
        public decimal NumSemestre { get; set; }

        public virtual EspModule CodeModuleNavigation { get; set; }
        public virtual EspModulePanierClasseSaiso EspModulePanierClasseSaiso { get; set; }
        public virtual Salle SalleNavigation { get; set; }
    }
}