// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class AMoyenne
    {
        public string IdEt { get; set; }
        public string CodeCl { get; set; }
        public string CodeModule { get; set; }
        public byte? Semestre { get; set; }
        public decimal? Moyenne { get; set; }
    }
}