// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class AValidationNote
    {
        public string CodeCl { get; set; }
        public string Module { get; set; }
        public decimal? Semestre { get; set; }
        public DateTime? VDate { get; set; }
    }
}