// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class ChampStr
    {
        public ChampStr()
        {
            Champ = new HashSet<Champ>();
        }

        public string CodeStr { get; set; }
        public string CodeChamp { get; set; }
        public string NomChamp { get; set; }
        public string MasqueChamp { get; set; }

        public virtual StrNome CodeStrNavigation { get; set; }
        public virtual ICollection<Champ> Champ { get; set; }
    }
}