// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Classe
    {
        public Classe()
        {
            EspDetailContrat = new HashSet<EspDetailContrat>();
            EspDispClass = new HashSet<EspDispClass>();
            EspEtudiant = new HashSet<EspEtudiant>();
            EspGroupeProjet = new HashSet<EspGroupeProjet>();
            EspSaisonClasse = new HashSet<EspSaisonClasse>();
        }

        public string CodeCl { get; set; }
        public string LibelleCl { get; set; }
        public string DescriptionCl { get; set; }
        public DateTime? DateCr { get; set; }
        public DateTime? DateDernModif { get; set; }
        public string SallePrincipale { get; set; }
        public string SelleSecondaire1 { get; set; }
        public string SalleSecondaire2 { get; set; }
        public bool? NiveauAccees { get; set; }
        public string Filiere { get; set; }
        public string AnneeScolaire { get; set; }
        public string LibFiliere { get; set; }
        public string CodeSpecialite { get; set; }
        public string LibSpecialite { get; set; }
        public string Categorie { get; set; }
        public string SiteEsp { get; set; }
        public string FiliereNew { get; set; }
        public string Mail { get; set; }

        public virtual ICollection<EspDetailContrat> EspDetailContrat { get; set; }
        public virtual ICollection<EspDispClass> EspDispClass { get; set; }
        public virtual ICollection<EspEtudiant> EspEtudiant { get; set; }
        public virtual ICollection<EspGroupeProjet> EspGroupeProjet { get; set; }
        public virtual ICollection<EspSaisonClasse> EspSaisonClasse { get; set; }
    }
}