// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class ComiteSpecialite
    {
        public int ComiteIdGrp { get; set; }
        public int SptsId { get; set; }

        public virtual Comite ComiteIdGrpNavigation { get; set; }
        public virtual Specialite Spts { get; set; }
    }
}