// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Comitevalidation
    {
        public int Idcomitevalidation { get; set; }
        public string Nom { get; set; }
        public string Specialite { get; set; }
    }
}