// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Compteur
    {
        public string CodeCpt { get; set; }
        public string LibCpt { get; set; }
        public DateTime? DateCr { get; set; }
        public DateTime? DateLastModif { get; set; }
    }
}