// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class ComptCert
    {
        public DateTime DateCert { get; set; }
        public string Heure { get; set; }
        public decimal Cpt { get; set; }
    }
}