// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class DateEnt
    {
        public string DateEnt1 { get; set; }
        public decimal? NombreCondidats { get; set; }
        public decimal? NombrMax { get; set; }
    }
}