// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Decid
    {
        public string IdDecid { get; set; }
        public string NomDecid { get; set; }
        public string TitreDecid { get; set; }
        public string EtatDecid { get; set; }
        public string PwdDecid { get; set; }
    }
}