// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class DemandeAttestationAlfikr
    {
        public string IdEt { get; set; }
        public string CodeCl { get; set; }
        public DateTime? JourSortie { get; set; }
        public string Heure { get; set; }
        public string NomPrenomPereEt { get; set; }
        public string NomPereEt { get; set; }
        public string PrenomPereEt { get; set; }
        public string NumeroCinPere { get; set; }
        public string TypeDemande { get; set; }
        public string CodeModule { get; set; }
        public string IdEns { get; set; }
        public string CauseAbsece { get; set; }
        public DateTime DateSaisie { get; set; }
        public string AnneeDeb { get; set; }
    }
}