// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Emploisemetud
    {
        public long Codemploi { get; set; }
        public string Idet { get; set; }

        public virtual EspEtudiant IdetNavigation { get; set; }
    }
}