// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EnteteReclamation
    {
        public decimal IdEnteteReclamation { get; set; }
        public string NomEns { get; set; }
        public string TypeReclamation { get; set; }
        public DateTime DateReclamation { get; set; }
        public string Designation { get; set; }
        public string IdEns { get; set; }
    }
}