// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspAuditConnexion
    {
        public DateTime? DateConnect { get; set; }
        public string Utilisateur { get; set; }
        public string NomProgram { get; set; }
        public string AdresseIp { get; set; }
        public string NomMachine { get; set; }
    }
}