// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspActiviteJoin
    {
        public string IdEt { get; set; }
        public string Confirmer { get; set; }
        public DateTime? DateSaisie { get; set; }
    }
}