// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspAdmis1415
    {
        public string IdEt { get; set; }
        public string NoteFr { get; set; }
        public string NoteAn { get; set; }
        public string NoteQi { get; set; }
    }
}