// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspAuditCredit
    {
        public string AnneeDeb { get; set; }
        public decimal? OldValCredit { get; set; }
        public decimal? NewValCredit { get; set; }
        public string AdresseIp { get; set; }
        public string Machine { get; set; }
        public DateTime DateOp { get; set; }
    }
}