// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspAideCours
    {
        public string IdEt { get; set; }
        public string NiveauAccees { get; set; }
        public string CodeCl { get; set; }
        public string CodeModule { get; set; }
        public DateTime DateCours { get; set; }
        public string HeurDebut { get; set; }
        public string HeurFin { get; set; }
    }
}