// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspArchivageEtudiant
    {
        public string IdEt { get; set; }
        public string TypeArchivage { get; set; }
        public DateTime DateArchivage { get; set; }
        public string MotifArchivage { get; set; }
        public string RespArchivage { get; set; }
        public string IpRchivage { get; set; }
        public string MachineArchivage { get; set; }
    }
}