// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspAppreciation
    {
        public string IdEt { get; set; }
        public string Apreciation { get; set; }
        public string Remediation { get; set; }
        public string AnneeDeb { get; set; }
        public decimal Priode { get; set; }
        public DateTime DateSaisaie { get; set; }
        public DateTime DateModif { get; set; }
        public string CodeDe { get; set; }
        public string NiveauScolaires { get; set; }
        public string CodeUe { get; set; }
    }
}