// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspAffGroupEtudiant
    {
        public EspAffGroupEtudiant()
        {
            EspSuiviProjetIndiv = new HashSet<EspSuiviProjetIndiv>();
        }

        public string IdGroupe { get; set; }
        public string AnneeDeb { get; set; }
        public string IdEt { get; set; }
        public DateTime? DateAffectation { get; set; }

        public virtual EspGroupeProjet EspGroupeProjet { get; set; }
        public virtual ICollection<EspSuiviProjetIndiv> EspSuiviProjetIndiv { get; set; }
    }
}