// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspCalcul
    {
        public string IdEt { get; set; }
        public decimal? ScoreEntretien { get; set; }
        public decimal? ScoreDossier { get; set; }
        public decimal? ScoreTest { get; set; }
        public decimal? ScoreFinal { get; set; }
        public decimal? ScoreFrancais { get; set; }
        public decimal? ScoreAnglais { get; set; }
        public decimal? ScoreQi { get; set; }
    }
}