// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspCoursSoutienEns
    {
        public bool Semestre { get; set; }
        public string CodeCl { get; set; }
        public string IdEt { get; set; }
        public string CodeModule { get; set; }
        public string IdEns { get; set; }
        public string AnneeDeb { get; set; }
    }
}