// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspCorrespondanceOkFikr
    {
        public string CodeClient { get; set; }
        public string CompteClient { get; set; }
    }
}