// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspDept
    {
        public string CodeDept { get; set; }
        public string LibelleDept { get; set; }
        public DateTime? DateCr { get; set; }
        public DateTime? DateDernierModif { get; set; }
    }
}