// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspDetailResultat
    {
        public string Codemati { get; set; }
        public string Libematifr { get; set; }
        public string Coefmati { get; set; }
        public string Typeep { get; set; }
        public string IdEt { get; set; }
        public string Rangmati { get; set; }
        public string NomEns { get; set; }
        public string Projectwork { get; set; }
        public string Oral { get; set; }
        public string Moyenneoraux { get; set; }
        public string Activitesdiverses { get; set; }
        public string Effort { get; set; }
        public string Notesuivi { get; set; }
        public string Test { get; set; }
        public string Tp1 { get; set; }
        public string Tp2 { get; set; }
        public string Dc1 { get; set; }
        public string Dc2 { get; set; }
        public string Ds { get; set; }
        public string Moyemati { get; set; }
    }
}