// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspDescpline
    {
        public string AnneeDeb { get; set; }
        public decimal NiveauScolaires { get; set; }
        public DateTime DateModif { get; set; }
        public DateTime DateSaisie { get; set; }
        public string DomaineEns { get; set; }
    }
}