// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspDevoirsMaison
    {
        public string IdEns { get; set; }
        public string CodeCl { get; set; }
        public string CodeModule { get; set; }
        public string Titre { get; set; }
        public string Sujet { get; set; }
        public DateTime DateSaisie { get; set; }
        public string AnneeDeb { get; set; }
        public string DateCt { get; set; }
        public string NumSeance { get; set; }
    }
}