// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspDomaineEnseignement
    {
        public string AnneeDeb { get; set; }
        public decimal NiveauScolaires { get; set; }
        public DateTime? DateSaisie { get; set; }
        public DateTime? DateModif { get; set; }
        public string DomaineEnseigement { get; set; }
        public decimal Priode { get; set; }
        public string UeEnseignement { get; set; }
        public string DescriptionUe { get; set; }
    }
}