// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspDetailContrat
    {
        public string Numord { get; set; }
        public string CodeCl { get; set; }
        public string CodeModule { get; set; }
        public byte NbHeures { get; set; }
        public string Periode { get; set; }

        public virtual Classe CodeClNavigation { get; set; }
        public virtual EspModule CodeModuleNavigation { get; set; }
    }
}