// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspDossiersScolaires
    {
        public string IdEt { get; set; }
        public string Etat { get; set; }
        public string AnneeDeb { get; set; }
        public string CodePiece { get; set; }
    }
}