// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspEmploi
    {
        public string CodeModule { get; set; }
        public string AnneeDeb { get; set; }
        public decimal Semestre { get; set; }
        public string CodeCl { get; set; }
        public decimal NumSeance { get; set; }
        public string Jour { get; set; }
        public string TypeSeance { get; set; }
        public DateTime? DateSaisie { get; set; }
    }
}