// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspEnseignantAbs
    {
        public string IdEns { get; set; }
        public DateTime DateAbs { get; set; }
        public string CodeModule { get; set; }
        public string CodeCl { get; set; }
        public bool NumSeance { get; set; }
        public string Motif { get; set; }
        public bool? NbHeures { get; set; }
        public string AnneeDeb { get; set; }
        public string TypeAbs { get; set; }
        public string CodeMotif { get; set; }
        public byte? NbMinutes { get; set; }
        public string Utilisateur { get; set; }
        public bool Semestre { get; set; }
        public string Observation { get; set; }
    }
}