// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspEtNotTransfFin
    {
        public string IdEt { get; set; }
        public string Numcompte { get; set; }
        public DateTime? DateSaisie { get; set; }
        public string JustifNotTransf { get; set; }
        public string Transferrred { get; set; }
        public DateTime? DateTransf { get; set; }
    }
}