// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Domain.Models
{
    public partial class EspEnseignant
    {
        [Key]
        public string IdEns { get; set; }
        public string NomEns { get; set; }
        public string TypeEns { get; set; }
        public DateTime? DateRec { get; set; }
        public string Niveau { get; set; }
        public DateTime? DateSaisie { get; set; }
        public DateTime? DateDernModif { get; set; }
        public string Etat { get; set; }
        public string Observation { get; set; }
        public string PwdEns { get; set; }
        public string PrenomEns { get; set; }
        public int? Cin { get; set; }
        public string SexeEns { get; set; }
        public string EtatCivilEns { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string CnssEns { get; set; }
        public DateTime? DnEns { get; set; }
        public DateTime? DeEns { get; set; }
        public DateTime? DsEns { get; set; }
        public int? Chefcomite { get; set; }
        public int? ComiteIdGrp { get; set; }
        public int? FkCmt { get; set; }
        public string TypeUp { get; set; }
        public string Up { get; set; }
        public DateTime? DateDebUp { get; set; }
        public string MailEns { get; set; }
        public string CodeGradeEntree { get; set; }
        public string LibGradeEntree { get; set; }
        public string CodeGradeActuel { get; set; }
        public string LibGradeActuelle { get; set; }
        public string Organisme { get; set; }
        public string PwdInit { get; set; }
        public string CodeDept { get; set; }
        public string ChefDept { get; set; }
        public string CodeEnsEduserv { get; set; }
        public string Nom { get; set; }
        public string Pnom { get; set; }
        public string Diplome { get; set; }
        public byte[] Image { get; set; }
    }
}