// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspEnseignantFichepfe
    {
        public string EspEnseignantIdEns { get; set; }
        public int FichepfesIdFiche { get; set; }

        public virtual Fichepfe FichepfesIdFicheNavigation { get; set; }
    }
}