// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspEvaluationScolaires
    {
        public string IdEt { get; set; }
        public decimal Apprentissage { get; set; }
        public string CodeDe { get; set; }
        public string Ue { get; set; }
        public string AnneeDeb { get; set; }
        public DateTime? DateSaisaie { get; set; }
        public DateTime? DateModif { get; set; }
        public decimal Priode { get; set; }
        public decimal NiveauScolaires { get; set; }
        public string IdEns { get; set; }
    }
}