// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspEtudiant2013
    {
        public string IdEt { get; set; }
        public string NumCinPasseport { get; set; }
        public string NomEt { get; set; }
        public string PnomEt { get; set; }
        public string EMailEt { get; set; }
        public string TelEt { get; set; }
        public string AdresseEt { get; set; }
        public string SpecialiteEspEt { get; set; }
        public string CodeCl { get; set; }
        public string AdresseMailEsp { get; set; }
        public string CodeClPrec { get; set; }
    }
}