// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspEtudiantNoteGroupe
    {
        public string IdGroupeProjet { get; set; }
        public string IdEt { get; set; }
        public byte NoteEt { get; set; }
        public string IdEns { get; set; }
        public string Remarque { get; set; }
        public string AbsEt { get; set; }
        public DateTime? DateEval { get; set; }
    }
}