// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspFiliere
    {
        public EspFiliere()
        {
            EspUe = new HashSet<EspUe>();
        }

        public string CodeFiliere { get; set; }
        public string LibFiliere { get; set; }

        public virtual ICollection<EspUe> EspUe { get; set; }
    }
}