// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspFichePfe
    {
        public int Idfiche { get; set; }
        public string Annee { get; set; }
        public string Cause { get; set; }
        public bool Convention { get; set; }
        public DateTime? Datedebuttraitement { get; set; }
        public DateTime? Datedebuttraitementenseignant { get; set; }
        public DateTime? Datedecision { get; set; }
        public DateTime? Datedepot { get; set; }
        public DateTime? Datevalidationencadrant { get; set; }
        public string Descriptionprojet { get; set; }
        public string Etat { get; set; }
        public string Rejetfiche { get; set; }
        public bool Soutenance { get; set; }
        public string Titreprojet { get; set; }
        public bool Validationencadrant { get; set; }
        public int? AnnulationfichepfeId { get; set; }
        public string CheffiliereCode { get; set; }
        public string CoencadrantCode { get; set; }
        public string DecisionCode { get; set; }
        public string DirectionstageCode { get; set; }
        public string EncadrantCode { get; set; }
        public string EnseignanatCode { get; set; }
        public string EnseignantCode { get; set; }
        public string EtudiantCode { get; set; }
        public int? SocieteIdsociete { get; set; }
        public string RapporteurCode { get; set; }
        public string Secteur { get; set; }
        public int? SectIdsecteur { get; set; }
        public int? Idsession { get; set; }
        public string Motifenseignant { get; set; }
        public DateTime? Daterelance { get; set; }
        public string AutorisationF { get; set; }
        public string AutorisationP { get; set; }
        public string Finance { get; set; }
        public string MotifNonComplet { get; set; }
        public string Pedagogique { get; set; }
        public string MotifRejetTech { get; set; }
        public bool? Asoutenir { get; set; }
        public string Attente { get; set; }
        public string Confidentiel { get; set; }
        public DateTime? DateDepotDossier { get; set; }
        public string BinomeCode { get; set; }
    }
}