// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspGpProjet
    {
        public string IdGroupeProjet { get; set; }
        public string NomGroupe { get; set; }
        public string Sujet { get; set; }
        public byte NumGroupe { get; set; }
        public string CodeCl { get; set; }
    }
}