// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspGroupeTarif
    {
        public string AnneeDeb { get; set; }
        public string CodeGrp { get; set; }
        public string LibelleGrp { get; set; }
        public decimal? MontantTarif { get; set; }
        public decimal? MontantTranche1 { get; set; }
        public DateTime? EcheanceTranche1 { get; set; }
        public decimal? MontantTranche2 { get; set; }
        public DateTime? EcheanceTranche2 { get; set; }
        public DateTime? DateSaisie { get; set; }
        public DateTime? DateMaj { get; set; }

        public virtual EspSaisonUniversitaire AnneeDebNavigation { get; set; }
    }
}