// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspImportscore
    {
        public string Matricule { get; set; }
        public string NoteAng { get; set; }
        public string NoteFran { get; set; }
        public string Noteqi { get; set; }
    }
}