// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspIdMoodle
    {
        public string IdMoodle { get; set; }
        public string F7 { get; set; }
    }
}