// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspJournalMdpEns
    {
        public string IdEns { get; set; }
        public DateTime? DateModif { get; set; }
        public string OldMdp { get; set; }
        public string NewMdp { get; set; }
        public string IpModif { get; set; }
        public string MachineModif { get; set; }
    }
}