// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspModule
    {
        public EspModule()
        {
            AffectationExamen = new HashSet<AffectationExamen>();
            EspAbsence = new HashSet<EspAbsence>();
            EspAbsenceList = new HashSet<EspAbsenceList>();
            EspAffectationEmploi = new HashSet<EspAffectationEmploi>();
            EspDetailContrat = new HashSet<EspDetailContrat>();
            EspEnteteAbsence = new HashSet<EspEnteteAbsence>();
            EspEnteteNote = new HashSet<EspEnteteNote>();
            EspEvaluation = new HashSet<EspEvaluation>();
            EspModuleEtudiant = new HashSet<EspModuleEtudiant>();
            EspModulePanierClasseSaiso = new HashSet<EspModulePanierClasseSaiso>();
            EspMoyModuleEtudiant = new HashSet<EspMoyModuleEtudiant>();
            EspProjet = new HashSet<EspProjet>();
            EspSeanceEns = new HashSet<EspSeanceEns>();
        }

        public string CodeModule { get; set; }
        public string Designation { get; set; }
        public string Description { get; set; }
        public decimal? NbHeures { get; set; }
        public string Etat { get; set; }
        public string Up { get; set; }
        public decimal? Coef { get; set; }
        public string NumPanier { get; set; }
        public string AEvaluer { get; set; }
        public string TypeEpreuve { get; set; }
        public string CodeMatiereEduserv { get; set; }

        public virtual EspUp UpNavigation { get; set; }
        public virtual ICollection<AffectationExamen> AffectationExamen { get; set; }
        public virtual ICollection<EspAbsence> EspAbsence { get; set; }
        public virtual ICollection<EspAbsenceList> EspAbsenceList { get; set; }
        public virtual ICollection<EspAffectationEmploi> EspAffectationEmploi { get; set; }
        public virtual ICollection<EspDetailContrat> EspDetailContrat { get; set; }
        public virtual ICollection<EspEnteteAbsence> EspEnteteAbsence { get; set; }
        public virtual ICollection<EspEnteteNote> EspEnteteNote { get; set; }
        public virtual ICollection<EspEvaluation> EspEvaluation { get; set; }
        public virtual ICollection<EspModuleEtudiant> EspModuleEtudiant { get; set; }
        public virtual ICollection<EspModulePanierClasseSaiso> EspModulePanierClasseSaiso { get; set; }
        public virtual ICollection<EspMoyModuleEtudiant> EspMoyModuleEtudiant { get; set; }
        public virtual ICollection<EspProjet> EspProjet { get; set; }
        public virtual ICollection<EspSeanceEns> EspSeanceEns { get; set; }
    }
}