// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspMessage
    {
        public string AnneeDeb { get; set; }
        public string IdEns { get; set; }
        public string IdEt { get; set; }
        public DateTime DateMessage { get; set; }
        public string ContenuMsg { get; set; }
        public string SubjetMsg { get; set; }
        public string SenderMsg { get; set; }
        public string TypeMsg { get; set; }
        public string DestMsg { get; set; }
        public string Etat { get; set; }
    }
}