// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspMoyUeEtudiant
    {
        public string AnneeDeb { get; set; }
        public string IdEt { get; set; }
        public string CodeUe { get; set; }
        public string CodeCl { get; set; }
        public bool? NiveauAcces { get; set; }
        public decimal? NbEcts { get; set; }
        public string TypeMoy { get; set; }
        public decimal? Moyenne { get; set; }
        public string Utilisateur { get; set; }

        public virtual EspUe EspUe { get; set; }
        public virtual EspEtudiant IdEtNavigation { get; set; }
    }
}