// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspMailEnseignant
    {
        public decimal Id { get; set; }
        public string NomEns { get; set; }
        public string MailEns { get; set; }
    }
}