// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspNiveauLangue
    {
        public string IdEt { get; set; }
        public string Langue { get; set; }
        public string AncienNiveau { get; set; }
        public string NiveauActuel { get; set; }
        public string IdEns { get; set; }
        public DateTime DateNiveau { get; set; }
    }
}