// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspNoteFikr
    {
        public string IdEt { get; set; }
        public string Nom { get; set; }
        public string IdEns { get; set; }
        public string NomEns { get; set; }
        public string CodeModule { get; set; }
        public string Designation { get; set; }
        public string CodeCl { get; set; }
        public string AnneeDeb { get; set; }
        public short NumSemestre { get; set; }
        public decimal? Orale { get; set; }
        public decimal? Tp { get; set; }
        public decimal? Dc1 { get; set; }
        public decimal? Dc2 { get; set; }
        public decimal? Ds { get; set; }
        public string AbsOr { get; set; }
        public string AbsDc1 { get; set; }
        public string AbsDc2 { get; set; }
        public string AbsDs { get; set; }
        public string AbsTp { get; set; }
        public DateTime? DateSaisie { get; set; }
    }
}