// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspObservationEnseignant
    {
        public string AnneeDeb { get; set; }
        public DateTime DateSaisieObs { get; set; }
        public string IdEns { get; set; }
        public string IdResp { get; set; }
        public string QualiteResp { get; set; }
        public string Observation { get; set; }
    }
}