// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspOrientation
    {
        public string AnneeDeb { get; set; }
        public string IdEt { get; set; }
        public string Ch1 { get; set; }
        public string Ch2 { get; set; }
        public string Ch3 { get; set; }
        public string Ch4 { get; set; }
        public string Specialite { get; set; }
        public string CodeCl { get; set; }
        public DateTime? DateSaisie { get; set; }
        public string Ch5 { get; set; }
        public string Ch6 { get; set; }
        public string Ch7 { get; set; }
        public string Ch8 { get; set; }
        public string Chfinal { get; set; }
    }
}