// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspRealise
    {
        public string IdDr { get; set; }
        public string Titre { get; set; }
        public decimal NbJours { get; set; }
        public string Resultat { get; set; }
        public string NomDr { get; set; }
    }
}