// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspSalleClasse
    {
        public decimal Id { get; set; }
        public decimal? AnneeDeb { get; set; }
        public string CodeCl { get; set; }
        public string Salle { get; set; }
    }
}