// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspSanction
    {
        public string IdEt { get; set; }
        public string CodeCl { get; set; }
        public decimal? Semestre { get; set; }
        public string Nature { get; set; }
        public string Motif { get; set; }
        public DateTime? DateSaisie { get; set; }
        public string AnneeDeb { get; set; }
        public string Observation { get; set; }
    }
}