// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspSession
    {
        public int IdAdmin { get; set; }
        public int Type { get; set; }
        public string Pwd { get; set; }
        public string Lgn { get; set; }
        public string EspensIdEns { get; set; }
    }
}