// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspScoreSpecialite
    {
        public string AnneeDeb { get; set; }
        public string CodeSpec { get; set; }
        public bool NiveauAcces { get; set; }
        public byte? CapaciteAccueuil { get; set; }
        public decimal? ScoreMin { get; set; }
    }
}