// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspTestEtud
    {
        public string IdEt { get; set; }
        public string TypeChoix { get; set; }
        public DateTime DateChoix { get; set; }
        public string TypeTest { get; set; }

        public virtual EspEtudiant IdEtNavigation { get; set; }
    }
}