// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspToeicNb
    {
        public DateTime? Datetest { get; set; }
        public decimal? Nbmax { get; set; }
        public decimal? NbCondidatsFr { get; set; }
        public decimal? NbCondidatsAng { get; set; }
    }
}