// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspTabPlanSalle
    {
        public bool? Groupe { get; set; }
        public string AnneeDeb { get; set; }
        public string AnneeFin { get; set; }
        public string CodeCl { get; set; }
        public string IdEt { get; set; }
        public string NomEt { get; set; }
        public string PnomEt { get; set; }
        public int? CritereTri { get; set; }
    }
}