// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspTraceCorrectNumcpt
    {
        public string IdEt { get; set; }
        public DateTime DateCorrect { get; set; }
        public string TypeCorrect { get; set; }
        public string OldNumcpt { get; set; }
        public string NewNumcpt { get; set; }
    }
}