// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspUe
    {
        public EspUe()
        {
            EspMoyUeEtudiant = new HashSet<EspMoyUeEtudiant>();
        }

        public string CodeUe { get; set; }
        public string LibUe { get; set; }
        public string CodeFiliere { get; set; }
        public decimal? NbEcts { get; set; }
        public byte? ChargeH { get; set; }
        public string TypeUe { get; set; }
        public string AnneeDeb { get; set; }
        public string NatureUe { get; set; }

        public virtual EspFiliere CodeFiliereNavigation { get; set; }
        public virtual ICollection<EspMoyUeEtudiant> EspMoyUeEtudiant { get; set; }
    }
}