// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class EspUe5emetelinfo
    {
        public string CodeUe { get; set; }
        public string LibUe { get; set; }
        public byte? NbEcts { get; set; }
        public byte? ChargeH { get; set; }
        public string CodeFiliere { get; set; }
    }
}