// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class FrCursus
    {
        public decimal IdCursus { get; set; }
        public string LibelleCursus { get; set; }
        public string AnneeCursus { get; set; }
        public string TypeCursus { get; set; }
        public string IdEns { get; set; }
        public string FinCursus { get; set; }
    }
}