// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class LiaisonNavScoNumtel
    {
        public string Numcompte { get; set; }
        public string NumTel { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
    }
}