// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Noteseminaire
    {
        public int Idnote { get; set; }
        public decimal Note { get; set; }
        public decimal Notecontrole { get; set; }
        public int? SeminaireIdseminaire { get; set; }
        public string EtudiantIdEt { get; set; }

        public virtual EspEtudiant EtudiantIdEtNavigation { get; set; }
        public virtual Seminaire SeminaireIdseminaireNavigation { get; set; }
    }
}