// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Presoutenance
    {
        public int IdPresoutenance { get; set; }
        public string Dte { get; set; }
        public string Heure { get; set; }
        public int? Etat { get; set; }
        public int? SessionpsoutIdsoutenance { get; set; }
        public string EtIdEt { get; set; }

        public virtual EspEtudiant EtIdEtNavigation { get; set; }
        public virtual Sessionpresoutenance SessionpsoutIdsoutenanceNavigation { get; set; }
    }
}