// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Quitus
    {
        public int Idquitus { get; set; }
        public string Encadeur { get; set; }
        public string Comite { get; set; }
        public string Etatfinancier { get; set; }
        public string Credit { get; set; }
        public string Depotrapport { get; set; }
        public string EtdIdEt { get; set; }

        public virtual EspEtudiant EtdIdEtNavigation { get; set; }
    }
}