// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class ResultatSemestre2
    {
        public string Codemati { get; set; }
        public string Libematifr { get; set; }
        public string Coefmati { get; set; }
        public string Rangmati { get; set; }
        public string Moyemati { get; set; }
        public string Codeperiexam { get; set; }
        public string Numeepre { get; set; }
        public string Libetypeeprefr { get; set; }
        public string IdEt { get; set; }
        public string Idenelev { get; set; }
        public string Noteepre { get; set; }
        public string Codetypeepre { get; set; }
    }
}