// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class ResultatFinalS12018
    {
        public string Idenelev { get; set; }
        public string Codeperiexam { get; set; }
        public string Moyeperiexam { get; set; }
        public string Rangperiexam { get; set; }
        public string Codedecicons { get; set; }
        public string Codesectorie { get; set; }
        public string Obsecons { get; set; }
        public string Codeprix { get; set; }
        public string Moyeexamnati { get; set; }
        public string Codementexam { get; set; }
        public string Codeetab { get; set; }
        public string Codecondassi { get; set; }
    }
}