// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Salle
    {
        public Salle()
        {
            AffectationExamen = new HashSet<AffectationExamen>();
        }

        public string CodeSalle { get; set; }
        public string Description { get; set; }

        public virtual ICollection<AffectationExamen> AffectationExamen { get; set; }
    }
}