// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Sessionetudiant
    {
        public int Idsessionet { get; set; }
        public string Password { get; set; }
        public string Matricule { get; set; }
        public string Email { get; set; }
    }
}