// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class Specialite
    {
        public int Id { get; set; }
        public string NomSpec { get; set; }

        public virtual ComiteSpecialite ComiteSpecialite { get; set; }
    }
}