// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class StrNome
    {
        public StrNome()
        {
            ChampStr = new HashSet<ChampStr>();
            CodeNomenclature = new HashSet<CodeNomenclature>();
        }

        public string CodeStr { get; set; }
        public string NomStr { get; set; }

        public virtual ICollection<ChampStr> ChampStr { get; set; }
        public virtual ICollection<CodeNomenclature> CodeNomenclature { get; set; }
    }
}