// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Domain.Models
{
    public partial class TypeMvt
    {
        public string TypeMvt1 { get; set; }
        public string LibelleType { get; set; }
        public DateTime? DateLastMvt { get; set; }
        public string CompteurAuto { get; set; }
        public int? NumAuto { get; set; }
        public byte? TailleCompteur { get; set; }
        public byte? CodePrix { get; set; }
        public string Designation { get; set; }
        public string Signe { get; set; }
    }
}